definitions:
  models.User:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      mobile:
        type: string
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  request.Register:
    properties:
      mobile:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - mobile
    - name
    - password
    type: object
info:
  contact: {}
paths:
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: object json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: 用户注册
      tags:
      - 用户管理
swagger: "2.0"
