name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
  #选择云端运行的环境
    runs-on: ubuntu-latest
    steps:
    #uses代表使用一个模块，此处使用的是checkout模块，将github项目文件导入到当前环境中
    - uses: actions/checkout@v1 # 将仓库内容拷贝到Ubuntu系统的虚拟环境
    - name: Build the Docker image # 步骤名字
      run: |
        docker login --username=${{ secrets.DOCKERHUB_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKERHUB_PASSWORD }} # 登录docker，并使用Secret里配置的参数
        docker build -t go-gin-api:latest . #执行构建
        docker tag go-gin-api registry.cn-hangzhou.aliyuncs.com/go_index/go-product:v1
        docker push registry.cn-hangzhou.aliyuncs.com/go_index/go-product:v1


